apiVersion: v1
kind: Pod
spec:
  containers:
  - name: maven
    image: baserepodev.devrepo.malibu-pctn.com/104017-malibu-artifacts/cloudbees-base-images/maven:3.6-jdk-8
    command: ['cat']
    tty: true
  - name: kaniko
    image: baserepodev.devrepo.malibu-pctn.com/104017-malibu-artifacts/cloudbees-base-images/kaniko-project/executor:debug
    imagePullPolicy: Always
    command:
    - /busybox/cat
    tty: true
    volumeMounts:
      - name: jenkins-docker-cfg
        mountPath: /kaniko/.docker
  volumes:
  - name: jenkins-docker-cfg
    projected:
      sources:
      - secret:
          name: devrepo-secret
          items:
            - key: .dockerconfigjson
              path: config.json
